# Autogenerated wrapper script for ROOT_julia_jll for x86_64-linux-gnu-julia_version+1.11.1
export libroot_julia

using libcxxwrap_julia_jll
using ROOT_jll
JLLWrappers.@generate_wrapper_header("ROOT_julia")
JLLWrappers.@declare_library_product(libroot_julia, "libroot_julia.so")
function __init__()
    JLLWrappers.@generate_init_header(libcxxwrap_julia_jll, ROOT_jll)
    JLLWrappers.@init_library_product(
        libroot_julia,
        "lib/libroot_julia.so",
        nothing,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
